### PR TITLE
use `data_rescale()`

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
https://github.com/easystats/datawizard/issues/53

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@mattansb Will this also be included in the next patch release?

**Comment by mattansb** [comment]
Wont this require the GH `datawizard`?

**Comment by IndrajeetPatil** [comment]
Nope, it's already in CRAN version.

image

**Comment by mattansb** [comment]
Then yes (:

**Pull request merged**
