### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
While you are working on miscellaneous things, Mattan, is there anything that can be cited to support this sentence [here](https://easystats.github.io/effectsize/reference/eta_squared.html):

Screenshot 2022-10-11 at 16 00 34

**Comment by mattansb** [comment]
I think the Lakens' paper? I'll check...

**Comment by mattansb** [comment]
image

http://daniellakens.blogspot.com/2015/06/why-you-should-use-omega-squared.html

---

Should I add this? @bwiernik is this reasonable?

**Comment by mattansb** [comment]
Hmm this paper seem to suggest that such negative values should be replaced with 0?

> The results presented in this article assure researchers that the common practice of replacing a negative estimate with zero for some prominent estimators is better than the MLE.

(p. 406)

Should we do this?

**Pull request merged**
