### PR TITLE
Use new pkgdown template

### PR DESCRIPTION
**Pull request by etiennebacher**
https://github.com/easystats/easystats/issues/186

### CODE REVIEW

**Review by IndrajeetPatil — COMMENTED** [review]
I think we need to retain some kind of structure under Articles. 

With the current changes, all articles will just be listed without any order or grouping. 

I think we should group articles like the following:

image

**Comment by etiennebacher** [comment]
The way I understand it is that using `navbar` to keep this structure for articles entirely overrides the layout specified in easystatstemplate (no dropdown on the right anymore, etc.). So I'm not sure we can use the template while customizing the way articles are organised (but I agree it's better to keep this structure).

But I'm not super familiar with pkgdown anyway

**Comment by IndrajeetPatil** [comment]
We are already doing this in _datawizard_:
https://github.com/easystats/datawizard/blob/c8a8959a3a91366dd1448f868ff4c8fb577286e1/_pkgdown.yml#L111-L120

So that can be used as a reference.

**Comment by etiennebacher** [comment]
Here's the output of my last commit when I build locally:

image

**Comment by IndrajeetPatil** [comment]
Looks great! Thanks a bunch.

**Review by IndrajeetPatil — APPROVED** [review]

**Comment by mattansb** [comment]
lol can't even follow what's up.
Sorry and thanks again to both of you!

**Pull request merged**
