### PR TITLE
Error with report.htest() #563

### LINKED ISSUE #563: Error with `report.htest()`
``` r
library(report)
library(datawizard)

data(iris)
set.seed(1234)
x <- data_filter(iris, Species != "versicolor")
x$Species <- as.character(x$Species)
x$Species[97:100] <- NA

t.test(x$Sepal.Length ~ x$Species, var.equal = TRUE) |> report()
#> Error: Grouping variable must be the same length.

t.test(Sepal.Length ~ Species, data = x, var.equal = TRUE) |> report()
#> Warning: Unable to retrieve data from htest object.
#>   Returning an approximate effect size using t_to_d().
#> Effect sizes were labelled following Cohen's (1988) recommendations.
#> 
#> The Two Sample t-test testing the difference of Sepal.Length by Species (mean
#> in group setosa = 5.01, mean in group virginica = 6.62) suggests that the
#> effect is negative, statistically significant, and large (difference = -1.61,
#> 95% CI [-1.82, -1.40], t(94) = -15.27, p < .001; Cohen's d = -3.15, 95% CI
#> [-3.75, -2.54])
```

### PR DESCRIPTION
**Pull request by strengejacke**
Fixed #563

### CODE REVIEW

**Comment by strengejacke** [comment]
``` r
library(effectsize)
library(datawizard)

data(iris)
x <- data_filter(iris, Species != "versicolor")
x$Species <- as.character(x$Species)
x$Species[97:100] <- NA

# works, but very large difference to other approach?
t.test(x$Sepal.Length ~ x$Species, var.equal = TRUE) |> effectsize()
#> Cohen's d |         95% CI
#> --------------------------
#> -3.12     | [-3.72, -2.52]
#> 
#> - Estimated using pooled SD.

t.test(Sepal.Length ~ Species, data = x, var.equal = TRUE) |> effectsize()
#> Warning: Unable to retrieve data from htest object.
#>   Returning an approximate effect size using t_to_d().
#> d     |         95% CI
#> ----------------------
#> -3.15 | [-3.75, -2.54]
```

<sup>Created on 2023-02-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
@mattansb This PR contains some lintr-related changes and I removed all `@import` tags, thus many changes are actually not related to the issue itself. The relevant change is only here:

image

I added tests, too. Maybe we should generally only keep complete cases, there are 1-2 further instances, where you simply omit missings per vector, which may result in unequal length of data.

**Comment by mattansb** [comment]
Okay, missing data is better dealt with in `.get_data_2_samples()`, so I completely removed the `na.omit`s from the `htest` functions (which are older bits of code).

Once all GHA pass, this can be merged (:

**Comment by mattansb** [comment]
Shit... I know what's happening.

Is this urgent for something? If not, I'll fix this on Sunday...

**Comment by strengejacke** [comment]
No, not urgent. :-)

**Comment by mattansb** [comment]
I've pushed a temp fix (until https://github.com/easystats/insight/issues/722 is resolved).

**Comment by strengejacke** [comment]
Do you have examples for all the combinations in your temp-fix?

**Comment by mattansb** [comment]
I think these are all the methods for fitting t.tests that can recover data

```R
# One sample
tt1 <- t.test(mtcars$mpg)
tt2 <- t.test(mtcars$mpg ~ 1)

# Two sample
tt3 <- t.test(mtcars$mpg ~ mtcars$am)
tt4 <- t.test(mtcars$mpg[mtcars$am==0], mtcars$mpg[mtcars$am==1])

# Paired
tt5 <- t.test(sleep$extra ~ sleep$group, paired = TRUE)
tt6 <- t.test(sleep$extra[sleep$group == "1"], sleep$extra[sleep$group == "2"], paired = TRUE)
tt7 <- t.test(Pair(sleep$extra[sleep$group == "1"], sleep$extra[sleep$group == "2"]) ~ 1)
```

**Comment by mattansb** [comment]
Should I merge this for now?

**Comment by strengejacke** [comment]
Yes, maybe also include a test for the _insight_ version, so the code won't break once https://github.com/easystats/insight/pull/723 is implemented?

**Comment by mattansb** [comment]
Errors seem to be unrelated to this PR.

**Pull request merged**
