### PR TITLE
dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
Here we go

### CODE REVIEW

**Comment by mattansb** [comment]
Do we have a (rough) timeline for when `effectsize` (and the updated `parameters`) will be available on CRAN?

**Comment by strengejacke** [comment]
_insight_ is on CRAN.

**Comment by strengejacke** [comment]
For bayestestR, do you think we can address https://github.com/easystats/bayestestR/issues/245?

**Comment by DominiqueMakowski** [comment]
Let me take a look now

**Comment by mattansb** [comment]
Why are the `interpret_*` functions in `effectsize`? Shouldn't they be in `report`?

Some fit in `effectsize`, sure... but `interpret_rhat`, `interpret_rope()`, `interpret_p()`?

I think they should either all be in their respective packages, or in `report`. Kinda weird having `interpret_bf` here...

**Comment by DominiqueMakowski** [comment]
I moved them all here. let it be the repo where we deal with the computation and interpretatio' of metrics, and its easier to group them all here (and document the implemented sets of rules of thumb here). report will then pull parameters and indices of performance from parameters and performance and their interpretation from here and then blend it in beautiful tables and neat text

**Pull request merged**
