### PR TITLE
MORE TESTS

### PR DESCRIPTION
**Pull request by mattansb**
Will we make it over 90%????

### CODE REVIEW

**Comment by mattansb** [comment]
So closeeeeee!!!
image

**Comment by mattansb** [comment]
Come onnnnnnn

image

@IndrajeetPatil I'm gonna do it!!!!

**Comment by IndrajeetPatil** [comment]
Yaay!! 🎉

**Comment by mattansb** [comment]
@IndrajeetPatil !!!!

image

**Comment by strengejacke** [comment]
You may now go to the next package and reach 90+ %! :-)

**Pull request merged**
