### PR TITLE
Adding a function for a "Ratio of Means" or "Response Ratio"

### PR DESCRIPTION
**Pull request by arcaldwell49**
# Description

This PR aims at adding a new effect size measure of a response ratio. The `rom` function will provide an estimate of a ratio of means using the approach detailed by Lajeunesse and Hedges. This effect size measure is often used in meta-analyses (particularly ecology), and is currently implemented in the `metafor` [R package](https://wviechtb.github.io/metafor/reference/escalc.html) (see the "ROM" and "ROMC" type `escalc`).

## References

Lajeunesse, M. J. (2011). On the meta‐analysis of response ratios for studies with correlated and multi‐group designs. Ecology, 92(11), 2049-2055 .https://doi.org/10.1890/11-0423.1

Lajeunesse, M. J. (2015). Bias and correction for the log response ratio in ecological meta‐analysis. Ecology, 96(8), 2056-2063. https://doi.org/10.1890/14-2402.1

Hedges, L. V., Gurevitch, J., & Curtis, P. S. (1999). The meta-analysis of response ratios in experimental ecology. Ecology, 80(4), 1150–1156. https://doi.org/10.1890/0012-9658(1999)080[1150:TMAORR]2.0.CO;2

# Proposed Changes

I have created the `rom` function to calculate the "response ratio" or the "ratio of means". Currently, only the function, its documentation, and unit tests are included. I have not included it in the vignettes/articles because I was unsure where to include such measures. My suggestion would be to include them under the "dominance" or "common language" measures.

### CODE REVIEW

**Comment by mattansb** [comment]
Looks good!

I've renamed the function to something more explicit:

``` r
library(effectsize)
x <- c(1.83,  0.50,  1.62,  2.48, 1.68, 1.88, 1.55, 3.06, 1.30)
y <- c(0.878, 0.647, 0.598, 2.05, 1.06, 1.29, 1.06, 3.14, 1.29)
means_ratio(x, y)
#> Means Ratio (adj.) |       95% CI
#> ---------------------------------
#> 1.31               | [0.82, 2.10]
```

<sup>Created on 2022-11-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


- [ ] Please take a look at the updated docs and vignette and let me know if those look okay.
- [ ] We are testing for strict positivity, but shouldn't zeros be allowed as well?

**Comment by mattansb** [comment]
Also, please add yourself (if you wish) in the DESCRIPTION file as a contributor (`[ctb]`)!

**Comment by arcaldwell49** [comment]
Okay, I think I addressed the issues raised above in my recent commit.

1. I have looked over the documentation and approve (just fixed a few typos).
2. You are right; zeroes should be allowed. A secondary test to ensure the mean is not zero has been added.
3. Completely agree, a `log` argument has been added to the function.

**Comment by mattansb** [comment]
Alright, looks good. Will merge once tests pass.

Thanks @arcaldwell49 !!

**Comment by arcaldwell49** [comment]
Awesome! Thanks for being open to the suggestions/function!

**Pull request merged**
