### PR TITLE
Cran 0.7.0.5

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Btw, _effectsize_ is the only package in the ecosystem that doesn't follow [semantic versioning](https://semver.org/). I think we should try to be internally consistent.

**Comment by mattansb** [comment]
Oops.... Sorry about that...

**Comment by strengejacke** [comment]
image

**Comment by mattansb** [comment]
> Thanks, on its way to CRAN.

**Pull request merged**
