### PR TITLE
more comprehensive buildignore; lintr config file

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by mattansb** [comment]
What's linr?

**Comment by IndrajeetPatil** [comment]
It detects lints (this is what the github action `lintr` is doing):
https://github.com/jimhester/lintr

`.lintr` config file helps you modify the defaults to our liking. For example, the defaults tag a line with more than 80 characters as a lint, but that is often too strict. So I've modified it here to be 120. Et cetera.

**Comment by IndrajeetPatil** [comment]
lol, I just realized there was a typo in my commit message 😅

**Comment by mattansb** [comment]
I have no idea what any of this does. But I trust you (:

**Pull request merged**
