### PR TITLE
new ES for Rank

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by mattansb** [comment]
Kinda weird that it's failing on a uppercase Eta, no? @bwiernik @IndrajeetPatil 

What is the function of the html5 check?

**Comment by mattansb** [comment]
The rank eta square is written with the uppercase Eta 🤷‍♂️ I'll just replace it with an H².

**Comment by bwiernik** [comment]
Got a link to that?

**Comment by mattansb** [comment]
Oops, it's $\eta^2_H$ 🤷‍♂️

**Pull request merged**
