### PR TITLE
add ci_method attribute

### PR DESCRIPTION
**Pull request by mattansb**
@IndrajeetPatil the `"ci_method"` attribute is a list giving the info, for example:
```R
list(method = "ncp", distribution = "t")
```

or

```R
list(method = "bootstrap", iterations = iterations)
```

----

- [x] Need to do `eta_squared()`

### CODE REVIEW

**Comment by mattansb** [comment]
@strengejacke @DominiqueMakowski Any idea how to fix this? (R3.4)

https://github.com/easystats/effectsize/runs/1848995806?check_suite_focus=true#step:10:76

It's bugging me!

**Comment by IndrajeetPatil** [comment]
The way to fix this is to remove all references to `car::` and `emmeans::` in `.Rd` docs. On `R-3.4`, these packaged are not available, and so the check complains about finishing these packages in the roxygen docs. 

That said, I have serious doubts about our choice to fall back to `3.4`, when widely used packages like `car`, `lme4`, `brms`, etc. all don't support this version. We are making our lives more difficult for nothing.

**Comment by mattansb** [comment]
image

But yeah, I tend to agree.

Will not removing these cause problems for anyone who wishes to install `effectsize` on R3.4? Or is this really just a warning?

**Comment by IndrajeetPatil** [comment]
It's just a `warning`. There will be no problem with installation, nor will there be any problem with any of the functionality. So this can be ignored. The CI checks will continue to fail though if `error_on_warning` is set to `TRUE`.

And, sure, fair enough about `lme4`, but my point is that the world has moved on from `3.4` long time ago, and I don't see any point in incentivizing people to keep using a buggy old version of R. But that's just my 2¢  🤷‍♂️

**Comment by mattansb** [comment]
> the world has moved on from 3.4 long time ago, and I don't see any point in incentivizing people to keep using a buggy old version of R. But that's just my 2¢ 🤷‍♂️

I agree.... modern R is, imo, R3.6+

**Pull request merged**
