### PR TITLE
CRAN 0.7

### PR DESCRIPTION
**Pull request by mattansb**
Part of https://github.com/easystats/easystats/issues/224

Waiting for the following to be uploaded to CRAN:

- [x] `datawizard` @IndrajeetPatil 
- [x] `parameters` @strengejacke

### CODE REVIEW

**Comment by strengejacke** [comment]
Ok, seems to work with latest _parameters_, I'll submit the next days. Just one question: we have now some redundancies related to the standardization vignettes:

https://easystats.github.io/parameters/articles/model_parameters_standardized.html
https://easystats.github.io/parameters/articles/standardize_parameters_effsize.html

The latter also mentions several effect sizes - wouldn't it be better to keep this vignette in _effectsize_?

**Comment by bwiernik** [comment]
It should move and be slightly rewritten to comment about other effect sizes available in *effectsize*

**Comment by mattansb** [comment]
Second what @bwiernik said (:

**Comment by mattansb** [comment]
@bwiernik need your latex expertise here https://win-builder.r-project.org/incoming_pretest/effectsize_0.7.0_20220525_090502/Windows/00check.log

@IndrajeetPatil You once showed a package that fixes broken URLs?

**Comment by IndrajeetPatil** [comment]
This one: https://github.com/r-lib/urlchecker

**Comment by IndrajeetPatil** [comment]
For more tools like this, see https://github.com/IndrajeetPatil/awesome-r-pkgtools/blob/master/README.md 😅

**Comment by mattansb** [comment]
All the urls pass this check - why is CRAN getting 503?

**Comment by bwiernik** [comment]
DOIs should use \doi{10.1234/567890} instead of being formatted as URLs. It's dumb and wrong, but it's CRAN policy and they will ask us to change it eventually

**Comment by bwiernik** [comment]
lastMiKTeXException is just saying that the LaTeX manual build ended in an error--it's coming from the errors above. 

Can you build the manual on your own system? There is probably a typo in the roxygen somewhere, or maybe an invalid Rd created

**Comment by mattansb** [comment]
> DOIs should use \doi{10.1234/567890} instead of being formatted as URLs. It's dumb and wrong, but it's CRAN policy and they will ask us to change it eventually.

The error are coming from DOIs that are already defined in `\doi{   }`, or ones that are pulled from a `.bib` file.... How the F do I solve this? ☹️

> Can you build the manual on your own system?

Can't get it working here. Can someone take a look?

**Comment by IndrajeetPatil** [comment]
@mattansb Can you please update to `roxygen2 7.2.0` and regenerate `.Rd`? 

I don't think that will solve anything, but I wanted to have a look at this and if I make any change on my computer and re-document, it will lead to large changes.

**Comment by strengejacke** [comment]
The 404 are indeed wrong URLs, the others are probably ignored by CRAN (had several 503, too, but no problem)

**Comment by mattansb** [comment]
Yes, I've fixed the 404.

So I will add a cran-comment about the other links.

Now just the manual...

**Comment by strengejacke** [comment]
I can look at it, but later today or tomorrow.

**Comment by strengejacke** [comment]
Should work now. I _think_ it was the empty line before the two `\cr` that caused the error.

**Comment by mattansb** [comment]
I keep doing that, don't I.... 😬

Thanks!

**Comment by mattansb** [comment]
Submitted again...

**Comment by mattansb** [comment]
> thanks, package effectsize_0.7.0.tar.gz is on its way to CRAN.

**Pull request merged**
