### PR TITLE
CRAN 0.4.0

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by mattansb** [comment]
Sent to win-builder...

**Comment by IndrajeetPatil** [comment]
If tests for any of my packages fail in `revdepcheck`, just tell the CRAN that the maintainer has been informed and will be submitting a revised version of the package soon.

**Comment by mattansb** [comment]
Set to CRAN. Some false alarm checks fail on winbuilder, addressed in submission *note*.
Hope it works....

**Comment by strengejacke** [comment]
what kind of warnings/errors? do you have a link?

**Comment by strengejacke** [comment]
?

**Comment by mattansb** [comment]
sorry - missed that: winbuilder seems to not "see" the new versions of insight / bayestestR, 
but this isn't an issue - all tests pass when submitting (only one tiny problem with a broken url...)

**Comment by strengejacke** [comment]
👍  ok.

**Comment by strengejacke** [comment]
> sorry - missed that: winbuilder seems to not "see" the new versions of insight / bayestestR,
> but this isn't an issue - all tests pass when submitting (only one tiny problem with a broken url...)

Ah yeah, I _think_ win-builder indeed relies on the built windows-binaries from CRAN, which are built some days later after the source package is released on CRAN

**Comment by mattansb** [comment]
> Thanks, on its way to CRAN.

(@IndrajeetPatil It does indeed break some of your stuff...)

I will publish a twitter thread of the new features tomorrow.

**Pull request merged**
