### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by mattansb**
- Insight version bump on on CRAN
- partial matching for interpretation rules' names

### CODE REVIEW

**Comment by mattansb** [comment]
@IndrajeetPatil @strengejacke Maybe relevant to https://github.com/easystats/parameters/issues/317:

``` r
library(effectsize)
library(BayesFactor)

data(raceDolls)
bf1 <- contingencyTableBF(raceDolls, sampleType = "poisson", fixedMargin = "cols")
effectsize(bf1, test = NULL)
#> # Description of Posterior Distributions
#> 
#> Parameter | Median |         89% CI
#> -----------------------------------
#> Cramers_v |  0.167 | [0.044, 0.281]
cramers_v(raceDolls)
#> Cramer's V |       95% CI
#> -------------------------
#>       0.17 | [0.00, 0.32]

bf2 <- ttestBF(mtcars$mpg[mtcars$am == 1], mtcars$mpg[mtcars$am == 0])
effectsize(bf2, test = NULL)
#> # Description of Posterior Distributions
#> 
#> Parameter | Median |         89% CI
#> -----------------------------------
#> Cohens_d  |  1.291 | [0.685, 2.036]
cohens_d(mtcars$mpg[mtcars$am == 1], mtcars$mpg[mtcars$am == 0])
#> Cohen's d |       95% CI
#> ------------------------
#>      1.48 | [0.67, 2.27]


bf3 <- correlationBF(iris$Sepal.Length, iris$Sepal.Width)
effectsize(bf3, test = NULL)
#> # Description of Posterior Distributions
#> 
#> Parameter | Median |          89% CI
#> ------------------------------------
#> r         | -0.115 | [-0.238, 0.011]
effectsize(cor.test(y = iris$Sepal.Length, x = iris$Sepal.Width))
#>     r |        95% CI
#> ---------------------
#> -0.12 | [-0.27, 0.04]
```

**Comment by IndrajeetPatil** [comment]
Me likely!

Were you thinking of returning these as parameters in model_parameters output for contingency tabs Bayes Factor tests?

**Comment by mattansb** [comment]
Not really - just wanted to add these effect sizes here (:
Not really sure if parameter is the place for these - parameter doesn't return effect sizes for most `htest` objects, and `BayesFactor` here is really just acting as a Bayesian-`htest` object too.

**Comment by mattansb** [comment]
@strengejacke I think this is what you were going for - I made it more generalizable:

``` r
library(glmmTMB)
library(parameters)
library(effectsize)

data(Salamanders)
Salamanders$DOP <- 10 * Salamanders$DOP

m1 <- glmmTMB(
  count ~ DOP + (1 | site),
  zi =  ~ DOP,
  family = poisson,
  data = Salamanders
)


effectsize::standardize_parameters(m1, method = "refit")
#> Component     |   Parameter | Coefficient (std.) |         95% CI
#> -----------------------------------------------------------------
#> conditional   | (Intercept) |               0.13 | [-0.46,  0.71]
#> conditional   |         DOP |               0.08 | [-0.01,  0.16]
#> zero_inflated | (Intercept) |              -0.49 | [-0.74, -0.24]
#> zero_inflated |         DOP |               0.18 | [-0.02,  0.38]
#> 
#> # Standardization method: Refit

effectsize::standardize_parameters(m1, method = "basic")
#> Warning: Non-refit parameter standardization is ignoring the zero-inflation
#> component.
#> Component     |   Parameter | Coefficient (std.) |         95% CI
#> -----------------------------------------------------------------
#> conditional   | (Intercept) |               0.00 | [ 0.00,  0.00]
#> conditional   |         DOP |               0.08 | [-0.01,  0.16]
#> zero_inflated | (Intercept) |              -0.49 | [-0.74, -0.24]
#> zero_inflated |         DOP |               0.02 | [ 0.00,  0.04]
#> 
#> # Standardization method: Basic



mp <- parameters::model_parameters(m1)

effectsize::standardize_parameters(mp, method = "basic")
#> Warning: Non-refit parameter standardization is ignoring the zero-inflation
#> component.
#> Component     |   Parameter | Coefficient (std.) |         95% CI
#> -----------------------------------------------------------------
#> conditional   | (Intercept) |               0.00 | [ 0.00,  0.00]
#> conditional   |         DOP |               0.08 | [-0.01,  0.16]
#> zero_inflated | (Intercept) |              -0.49 | [-0.74, -0.24]
#> zero_inflated |         DOP |               0.02 | [ 0.00,  0.04]
#> 
#> # Standardization method: Basic
```

<sup>Created on 2020-10-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
@strengejacke ?

**Comment by strengejacke** [comment]
Sorry, wasn't looking at this notifications for the dev in detail. Yes, looks good!

**Pull request merged**
