### PR TITLE
add linting and code coverage actions; let's see if it works

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Awesome, everything works!

Also, code coverage is at 72%, so shouldn't be too difficult to get it to > 95% (cf. https://github.com/easystats/easystats/issues/101).

**Comment by mattansb** [comment]
Is that good, bad? (I'm really asking how I compare to @strengejacke 😅)

Can you add a badge (of shame?) to the README?

**Comment by IndrajeetPatil** [comment]
Hmm, there is an error here. The code coverage badge is computing it on **master** branch, which is now defunct. It should be called **main** branch.

**Comment by mattansb** [comment]
No way to fix that? :(

**Comment by strengejacke** [comment]
> Is that good, bad? (I'm really asking how I compare to @strengejacke 😅)
> 
> Can you add a badge (of shame?) to the README?

Ok, 61% vs 50% - but you get -15% for failing tests, so I have the lead currently. 😎

**Comment by mattansb** [comment]
But my tests are failing because parameters doesn't actually work on R3.4 (see bug I opened)... So you're cheating!

**Pull request merged**
