### PR TITLE
fix Bayes std_param

### PR DESCRIPTION
**Pull request by mattansb**
now has CI

- [ ] add tests for this

### CODE REVIEW

**Comment by mattansb** [comment]
@DominiqueMakowski @strengejacke 
Any idea how to fix this Travis error?

> Error: package ‘Rcpp’ was installed before R 4.0.0: please re-install it

**Comment by strengejacke** [comment]
> namespace ‘parameters’ 0.6.1 is being loaded, but >= 0.6.1.1 is required

**Comment by strengejacke** [comment]
> Error: package ‘Rcpp’ was installed before R 4.0.0: please

I think this is rather related to travis and the switch to R 4.0

**Comment by mattansb** [comment]
@strengejacke Safe to ignore both of these?

**Comment by strengejacke** [comment]
I'd say yes, as you can't do anything about it, anyway. Travis downloads the latest package versions from CRAN, and if you need functions from _parameters_, which are not on CRAN yet, it'll fail anyway. Before submission to CRAN, I'd revisit the logs from Travis, as these indicate possible reverse dependency errors, as in this particular case.

**Pull request merged**
