### PR TITLE
Minor d effect sizes stuff

### PR DESCRIPTION
**Pull request by mattansb**
@IndrajeetPatil Take notice to some of these changes.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Thanks for the heads-up!

Will require just minor tweaks to tests and `statsExpressions` should be fine.

**Comment by bwiernik** [comment]
There’s a better correction still using the gamma function. I suggest we drop both of these approximations and just use the gamma function.  https://github.com/psychmeta/psychmeta/blob/34fec04d94538c86d7b0a0735ce0320270ce7951/R/correct_d.R#L44

@mattansb

**Comment by mattansb** [comment]
@bwiernik How is that different from this?
https://github.com/easystats/effectsize/blob/main/R/cohens_d.R#L300

**Comment by bwiernik** [comment]
That's the same. The hedges and Hunter methods are approximations to that from an era when the gamma function wasn't readily available.

**Pull request merged**
