### PR TITLE
fix CRAN unicode issue

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by mattansb** [comment]
@rempsyc @IndrajeetPatil Anything to do with these failures on `ubuntu-latest (devel) zh_CN`?

**Comment by IndrajeetPatil** [comment]
It's a spurious build failure. Ignore it. Retriggering that particular job will typically fix it.

**Comment by IndrajeetPatil** [comment]
Also, in CRAN comments, note that you checked this using the appropriate platform.

And, of course, do check if this PR indeed fixes the issue 😅

```r
rhub::check("effectsize_x.y.z.tar.gz", platforms = "debian-clang-devel")
```

`{rhub}` also supports some other platform, just in case you wanted to be comprehensive:

``` r
rhub::platforms()
#> debian-clang-devel:
#>   Debian Linux, R-devel, clang, ISO-8859-15 locale
#> debian-gcc-devel:
#>   Debian Linux, R-devel, GCC
#> debian-gcc-devel-nold:
#>   Debian Linux, R-devel, GCC, no long double
#> debian-gcc-patched:
#>   Debian Linux, R-patched, GCC
#> debian-gcc-release:
#>   Debian Linux, R-release, GCC
#> fedora-clang-devel:
#>   Fedora Linux, R-devel, clang, gfortran
#> fedora-gcc-devel:
#>   Fedora Linux, R-devel, GCC
#> linux-x86_64-rocker-gcc-san:
#>   Debian Linux, R-devel, GCC ASAN/UBSAN
#> macos-highsierra-release:
#>   macOS 10.13.6 High Sierra, R-release, brew
#> macos-highsierra-release-cran:
#>   macOS 10.13.6 High Sierra, R-release, CRAN's setup
#> solaris-x86-patched:
#>   Oracle Solaris 10, x86, 32 bit, R-release
#> solaris-x86-patched-ods:
#>   Oracle Solaris 10, x86, 32 bit, R release, Oracle Developer Studio 12.6
#> ubuntu-gcc-devel:
#>   Ubuntu Linux 20.04.1 LTS, R-devel, GCC
#> ubuntu-gcc-release:
#>   Ubuntu Linux 20.04.1 LTS, R-release, GCC
#> ubuntu-rchk:
#>   Ubuntu Linux 20.04.1 LTS, R-devel with rchk
#> windows-x86_64-devel:
#>   Windows Server 2022, R-devel, 64 bit
#> windows-x86_64-oldrel:
#>   Windows Server 2022, R-oldrel, 32/64 bit
#> windows-x86_64-patched:
#>   Windows Server 2022, R-patched, 32/64 bit
#> windows-x86_64-release:
#>   Windows Server 2022, R-release, 32/64 bit
```

<sup>Created on 2022-10-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattansb** [comment]
That seems to have worked (@strengejacke for insight)
Will submit tomorrow.

**Comment by IndrajeetPatil** [comment]
> That seems to have worked 

@mattansb Did you check with rhub on the respective platform?

**Comment by mattansb** [comment]
No, I'll do that tomorrow - but the same issue was on dev- Ubuntu here on gh actions, and seems to be resolved.

**Comment by mattansb** [comment]
> Dear maintainer,
>
> thanks, package effectsize_0.8.1.tar.gz is on its way to CRAN.

**Pull request merged**
