### PR TITLE
NEW: API

### PR DESCRIPTION
**Pull request by mattansb**
There are 3 major functions that need a reliable API. This is the goal for version 1.0.0

## `eta_squared()`

Essentially any model that can produce one of 3 tables will be supported:
- [x] Basic (aov)
- [x] Multi-level (aovlist)
- [x] Approx (anova-F)

And also:
- [x] `parameters_model` - it should be possible to get the effect size without having to also call `parameters`!
   - [x] Waiting for https://github.com/easystats/parameters/issues/624
   - [x] split by response, if present

## `standardize.default()`

- [x] Nothing to do, really.
- [x] Check `standardize.mlm()` - waiting for https://github.com/easystats/datawizard/issues/42
- [x] Check `standardize.coxph()`

## `standardize_parameters()`

- [x] For "refit" need to be supported in `standardize`.
- [x] For post hoc methods, needs to be supported by `standardize_info`
- [ ] Fix for multivariate models https://github.com/easystats/effectsize/issues/398

And also:
- [x] `parameters_model` - it should be possible to get the effect size without having to also call `parameters`!
    - [ ] Have `standardize_parameters()` use `standardize_parameters.parameters_model()` for complete usage. 

### `standardize_info()`

- [x] Add more info to the vignette.

### CODE REVIEW

**Comment by bwiernik** [comment]
>  the only way to break the circle would be if parameters stopped returning standardized effect sizes completely.

Or if the standardize function moved to *parameters*

**Comment by DominiqueMakowski** [comment]
> if parameters stopped returning standardized effect sizes completely.

and to move the "current" parameters table (i.e., params, effectsizes) to report

**Comment by bwiernik** [comment]
Now, I'm confused again. parameters depends on effectsize because it needs the standardize functions. So, if those were in parameters, effectsize would be entirely downstream of parameters and the problem goes away. 

I don't see why anything should move to report (and in general I think it should not).

**Comment by strengejacke** [comment]
> if those were in parameters, 

They were in the beginning. But then some weird psychologists argued that a standardized coefficient is an effect size, and thus we moved the standardize functions to that package...

**Comment by mattansb** [comment]
Not only the standardization would neen to be moved to parameters, also the ANOVA effect size functions and the `effectsize.htest()` (which depends on `cohens_d()`, `rank_biserial()`, etc....). So literally everything, except for the `interpret` functions (which, as we all know, *should* be in `report`).

**Comment by mattansb** [comment]
Post-hoc standardize_parameters() API is getting too big - merging this for now.

**Pull request merged**
