### PR TITLE
rbs parametric CIs

### PR DESCRIPTION
**Pull request by mattansb**
#279 

Seems to work.
But I am hesitant to use a method without a proper reference to it... 
Pinging @bwiernik who seems to have a clue? ^_^

### CODE REVIEW

**Comment by bwiernik** [comment]
Here is a detailed treatment of variances for correlations under different designs https://doi.org/10.1037/a0033788

But otherwise, these look like delta-method SEs based on transforming d values to correlations. The 4 * N / (n1 * n2) construction is the "effective sample size" (see ?psychmeta::ma_d or https://arxiv.org/abs/1903.01362 or Hedges Olkin 1985 p110).

I haven't checked the formulas in detail, but this appears to be what's going on at a quick glance.

**Comment by mattansb** [comment]
Yeah, I figures that this was Fisher's transformation, but I can't locate any source for those SEs being used.
I guess we'll have to trust the gods of JASP...

**Comment by bwiernik** [comment]
No, I mean the various parts look like (1) SE for Cohen's d and (2) delta method for a transformation to z. Just haven't sat down to double check them.

**Comment by mattansb** [comment]
This
https://github.com/easystats/effectsize/pull/322/files#diff-fce99caf6fa6a762be18ebbbc3dcddd3d144fe44f3a86029b8eb259b4cae80f2R204

And this?

https://github.com/easystats/effectsize/pull/322/files#diff-fce99caf6fa6a762be18ebbbc3dcddd3d144fe44f3a86029b8eb259b4cae80f2R209

Anyway, when you get the chance to validate, let me know ^_^

**Comment by IndrajeetPatil** [comment]
So this change won't be making it to the next release, correct?

**Comment by mattansb** [comment]
I think it will, question is will @bwiernik have time to look at the SE equations before hand? 😅

**Comment by bwiernik** [comment]
What's my deadline 😅

**Comment by mattansb** [comment]
Pressure is mounting to get effectsize out...

@bwiernik If you can get to it over the next couple of days (say... by Tuesday?) that'd be great.
If not, @IndrajeetPatil I think this will wait for the next release :/ I really don't feel comfortable putting out something without a clue to if/why it works.

**Comment by bwiernik** [comment]
Will try to look tomorrow

**Comment by mattansb** [comment]
Merging... @bwiernik we can pick this up in #336 at some point (:

**Pull request merged**
