### PR TITLE
revdep and cran comments

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by mattansb** [comment]
Oops, already submitted.

**Comment by IndrajeetPatil** [comment]
Yeah, no worries. But maybe you can still merge this after the package is accepted?

We can use these as template files for the future releases.

**Comment by strengejacke** [comment]
are these reports automatically created? I always struggle with revdep checks. these often fail when a package is (temporarily) not available etc.

**Comment by IndrajeetPatil** [comment]
Yes. I do the following:

```r
library(revdepcheck)

revdep_check(num_workers = 4)
revdep_report()
revdep_reset()
```

I then copy-paste the contents of `CRAN.md` it generates to `cran-comments.md`.

**Comment by strengejacke** [comment]
> statsExpressions

> The maintainer of this package confirms that the failure is unrelated to the effectsize update and should resolve itself with the new release (statsExpressions 1.0.0).

I bet you get a 3-month-ban from CRAN submissions this year. :-D

**Pull request merged**
