### PR TITLE
Fix Kendall's W with ties

### PR DESCRIPTION
**Pull request by mattansb**
_Closing #448_

I would rather not use the formula used by `DescTools` since I can't find where it came from.

The alternative is to drop the tie-correction all together.

### CODE REVIEW

**Comment by mattansb** [comment]
> vegan::kendall.global() uses a formula very close to yours and find W = 0.6147, which is probably the right result since it is also the one reported by irr::kendall(correct = TRUE) and synchrony::kendall.w() with different formulas.

I wonder if they are all copying from each other...

> However, the ranking seems to be applied by columns while you do it by rows.

Yes, I am being consistent with `friedman.test`, while everyone else seems not to be for some reason (?)

Doesn't it make sense to have raters on rows? IDK...

**Comment by bwiernik** [comment]
I tend to store my data as cases on rows and raters on columns (eg, coworker1, coworker2). Perhaps we should have an argument to control which is which (which we implement by transposing the data)?

**Comment by mattansb** [comment]
Yeah, that's easy enough to do.

``` r
RoundingTimes <-
  matrix(c(5.40, 5.50, 5.55,
           5.85, 5.70, 5.75,
           5.20, 5.60, 5.50,
           5.55, 5.50, 5.40,
           5.90, 5.85, 5.70,
           5.45, 5.55, 5.60,
           5.40, 5.40, 5.35,
           5.45, 5.50, 5.35,
           5.25, 5.15, 5.00,
           5.85, 5.80, 5.70,
           5.25, 5.20, 5.10,
           5.65, 5.55, 5.45,
           5.60, 5.35, 5.45,
           5.05, 5.00, 4.95,
           5.50, 5.50, 5.40,
           5.45, 5.55, 5.50,
           5.55, 5.55, 5.35,
           5.45, 5.50, 5.55,
           5.50, 5.45, 5.25,
           5.65, 5.60, 5.40,
           5.70, 5.65, 5.55,
           6.30, 6.30, 6.25),
         nrow = 22,
         byrow = TRUE,
         dimnames = list(1 : 22,
                         c("Round Out", "Narrow Angle", "Wide Angle")))

effectsize::kendalls_w(RoundingTimes)
#> Kendall's W |       95% CI
#> --------------------------
#> 0.25        | [0.06, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].

effectsize::kendalls_w(t(RoundingTimes), blocks_on_rows = FALSE)
#> Kendall's W |       95% CI
#> --------------------------
#> 0.25        | [0.09, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at [1.00].
```

<sup>Created on 2022-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mattansb** [comment]
@etiennebacher So `DescTools::KendallW()`, `irr::kendall()` and `synchrony::kendall.w()` are all using the same formula that is different than the one on Wikipedia (the code for `DescTools::KendallW()` and `irr::kendall()` is also identical, so some copying was done here, so not independent sources of info).

**Comment by mattansb** [comment]
FIXED!

``` r
m <- statsExpressions::bugs_long |> 
  subset(select = c(subject, condition, desire)) |> 
  datawizard::reshape_wider(values_from = "desire", 
                            colnames_from = "condition", 
                            rows_from = "subject") |> 
  na.omit() |>
  as.matrix() |> 
  subset(select = c(2:5))

effectsize::kendalls_w(desire ~ condition | subject, 
                       data = statsExpressions::bugs_long,
                       ci = NULL)[[1]]
#> [1] 0.2114916

effectsize::kendalls_w(m, ci = NULL)[[1]]
#> [1] 0.2114916

effectsize::kendalls_w(t(m), blocks_on_rows = FALSE, ci = NULL)[[1]]
#> [1] 0.2114916

DescTools::KendallW(t(m), correct = TRUE)
#> [1] 0.2114916

irr::kendall(t(m), correct = TRUE)[["value"]]
#> [1] 0.2114916

synchrony::kendall.w(t(m))[["w.corrected"]]
#> [1] 0.2114916

vegan::kendall.global(t(m))$Concordance_analysis[1]
#> [1] 0.2114916
```

<sup>Created on 2022-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Pull request merged**
