### PR TITLE
new: interpret.effectsize_table

### PR DESCRIPTION
**Pull request by mattansb**
#294

Still need to add some tests....

### CODE REVIEW

**Comment by mattansb** [comment]
Um, why are all the tests failing due to installation of dependencies?

**Comment by mattansb** [comment]
@IndrajeetPatil Any idea why this PR is failing to install dependencies, if it has the same deps (same description file) as `main`, which isn't failing?

**Comment by IndrajeetPatil** [comment]
Seems to be working. 

Sometimes the actions have problems accessing the repos because of technical snags with GitHub API. 🤷‍♂️

**Comment by mattansb** [comment]
So weirddddddd

Thanks!

**Pull request merged**
