### PR TITLE
CRAN 0.3.1

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by mattansb** [comment]
@DominiqueMakowski @strengejacke any idea how to deal with this vignette build warning?

https://cran.r-project.org/web/checks/check_results_effectsize.html

**Comment by mattansb** [comment]
Oh, never mind - on its way to CRAN (:

**Comment by strengejacke** [comment]
I'm not sure, but it looks like this code, in particular `estimate_density()` or inside `see::plot()`, produces NAs... Might be a temporal issue, or a different handling on Linux?

```r
library(bayestestR)
library(see)

data.frame(VarWise = Z_VariableWise$Subjective_Valence,
           ParWise = Z_ParticipantWise$Subjective_Valence,
           Full = Z_Full$Subjective_Valence) %>% 
  estimate_density(method="kernSmooth") %>% 
  plot() +
  see::theme_modern()
```

**Comment by strengejacke** [comment]
oh, great! :-)

**Pull request merged**
