### PR TITLE
Cran 0.8

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Don't forget to mention in `cran_comments.md` that this update will break _statsExpressions_ and the maintainer has been informed.

**Comment by strengejacke** [comment]
Do you want to merge main into this PR?

**Comment by mattansb** [comment]
Stupid winbuilder, telling me that "et al" has two misspelt words...

**Comment by IndrajeetPatil** [comment]
Yeah, they should really stop with spell checking the DESCRIPTION files.

**Comment by IndrajeetPatil** [comment]
Happened to me as well during incoming checks. I cc'ed Uwe and let him know that it's a false positive. And the submission was approved.

**Comment by mattansb** [comment]
Submitting now..

**Comment by mattansb** [comment]
> Thanks, on its way to CRAN.
>
> Team: Yet again breakage of statsExpressions ...

Tomorrow I'll make the release + tweet about all the new features 💪

**Pull request merged**
