### PR TITLE
New CRAN release 

### PR DESCRIPTION
**Pull request by mattansb**
deal with #648

### CODE REVIEW

**Comment by mattansb** [comment]
@strengejacke @IndrajeetPatil Any idea why some tests are still failing when `effectsize` no longer uses the `effectsize_type` argument anywhere?

**Comment by IndrajeetPatil** [comment]
You need to use parameters 0.22.0, which has renamed this parameter.

**Comment by strengejacke** [comment]
It's indeed strange, we have this warning only since _parameters 0.22.0_?

**Comment by strengejacke** [comment]
You're calling, e.g. from `.anova_es.aov()`:

```r
params <- parameters::model_parameters(model, verbose = verbose, effects = "fixed", es_type = NULL)
```

the `.aov` method from `model_parameters` has no `effects` argument, and this partially matches with the deprecated, but not yet removed(!) argument `effectsize_type`. The only way to fix this is to remove the `effects` argument.

**Comment by IndrajeetPatil** [comment]
Oh boy. Okay, I have changed some options to make sure that we always get warnings if we are using partial matching anywhere.  

You should see new warnings from now on about this issue.

**Comment by strengejacke** [comment]
Our goal was to remove that partial matching by renaming that argument in _parameters_, although there were no warnings, so Mattan can use both `effects` and `es_type` in his _effectsize_ package - and now we actually made things worse (at least temporary...) 🙄

**Comment by strengejacke** [comment]
@mattansb Do we need to set `effects = "fixed"` in the anova methods at all? That argument doesn't exist in `parameters::model_parameters()` for anova objects.

**Comment by mattansb** [comment]
We do :/ some non-ANOVA objects get passed down there...
Is there a `verbose = FALSE` option to suppress that partial matching warning?

**Comment by strengejacke** [comment]
No, there's not. 😞 
Maybe we wrap the call into `suppressWarnings+)`?

**Comment by IndrajeetPatil** [comment]
You can also change the options generating warnings about partial matching using `on.exit()` for the scope of the function where this warning originates.

**Comment by mattansb** [comment]
But I want to capture other warnings...

I think I'll have to use:

``` r
foo <- function(x) {
  if (x == 1) {
    warning("something something effectsize_type...")
  } else {
    warning("some other warning...!")
  }
  x + 1
}

foo(1)
#> Warning in foo(1): something something effectsize_type...
#> [1] 2

foo(2)
#> Warning in foo(2): some other warning...!
#> [1] 3
```


```R
withCallingHandlers({
  foo(1)
}, warning = function(w) {
  if (grepl("effectsize_type...", conditionMessage(w))) {
    invokeRestart("muffleWarning")
  }
})
#> [1] 2
```


```R
withCallingHandlers({
  foo(2)
}, warning = function(w) {
  if (grepl("effectsize_type...", conditionMessage(w))) {
    invokeRestart("muffleWarning")
  }
})
#> Warning in foo(2): some other warning...!
#> [1] 3
```

<sup>Created on 2024-06-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
> I'm sure it will come up eventually (:

I'd say we quickly remove the deprecation warning in _parameters_, and add back the `effects` argument then. Maybe we add a "TODO" as comment to the code?

**Comment by strengejacke** [comment]
> but I remember that argument was there for a reason

I think I also read an issue about this, but cannot quite remember when and where.

**Comment by strengejacke** [comment]
Was it related to the _report_ package? Or because we could have parameter effect sizes for mixed models, and therefore needed to set  `effects = "fixed"`?

**Comment by mattansb** [comment]
No idea 🤷‍♂️
We test mixed models, so it's not it.

Anyway, submitted.

**Comment by mattansb** [comment]
> Thanks, on its way to CRAN.

**Pull request merged**
