### PR TITLE
CRAN 0.8.3

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by mattansb** [comment]
@IndrajeetPatil Where do I see the results from `revdepcheck`?

**Comment by IndrajeetPatil** [comment]
Here: https://github.com/easystats/effectsize/actions/runs/4031637204/jobs/6931041009

**Comment by IndrajeetPatil** [comment]
All looks good:

```r
── CHECK ──────────────────────────────────────────────────────── 19 packages ──
OK: 19
BROKEN: 0
Total time: 1 hour
```

**Comment by mattansb** [comment]
Okay thanks!

Your GHA have made this CRAN puch _soooo easyyyy_ <3

**Comment by strengejacke** [comment]
How do we trigger revdep check again? Have forgotten...

**Comment by IndrajeetPatil** [comment]
cf. https://github.com/easystats/workflows/issues/21#issuecomment-1377807668

**Comment by mattansb** [comment]
DAMN, that was FAST!

> thanks, package effectsize_0.8.3.tar.gz is on its way to CRAN.

**Comment by IndrajeetPatil** [comment]
Awesome!

**Pull request merged**
