### PR TITLE
CRAN 1.0.0

### PR DESCRIPTION
**Pull request by mattansb**
As part of https://github.com/easystats/easystats/issues/434

- [x] run revdepcheck
- [x] run win-builder

### CODE REVIEW

**Comment by strengejacke** [comment]
Looks good! Remove `Remotes` again and go ahead!

**Review by strengejacke — APPROVED** [review]

**Comment by mattansb** [comment]
Looks good 🤩

**Comment by mattansb** [comment]
- [ ] run revdepcheck
- [ ] run win-builder

**Comment by mattansb** [comment]
I ran a `revdepcheck`, which found some errors the are related to performance and datawizard (so false alarms as far as effectsize is concerend).

Sending to winbuilder.

**Comment by mattansb** [comment]
_thanks, package effectsize_1.0.0.tar.gz is on its way to CRAN._

🥳🥳🥳

**Pull request merged**
