### PR TITLE
Use `datawizard::weighted_*`

### PR DESCRIPTION
**Pull request by mattansb**
https://github.com/easystats/datawizard/pull/100

### CODE REVIEW

**Comment by mattansb** [comment]
@IndrajeetPatil @strengejacke Tests here are failing due to something going on in the dev-version of datawizrd:

E.g.:

```
Warning (test-standardize_parameters.R:331:5): standardize_parameters (Pseudo - GLMM)
Following variable(s) were not found: SE, Std. Error
Backtrace:
  1. testthat::expect_warning(...)
       at test-standardize_parameters.R:331:4
  8. effectsize::standardize_parameters.default(...)
       at effectsize/R/standardize_parameters.R:158:2
 10. parameters:::model_parameters.merMod(...)
 12. parameters:::.extract_parameters_mixed(...)
 13. datawizard::data_remove(parameters, c("SE", "Std. Error"))
 14. datawizard:::.evaluated_pattern_to_colnames(...)
       at datawizard/R/data_remove.R:38:2
```

(I don't get these when I run the tests interactively.)

**Comment by strengejacke** [comment]
Set verbose to FALSE in data_remove

**Comment by mattansb** [comment]
Then that should be done in `parameters`, no?

**Comment by strengejacke** [comment]
should already be the case:
https://github.com/easystats/parameters/search?q=data_remove

**Comment by mattansb** [comment]
Hmmm let me run the tests again.

**Comment by mattansb** [comment]
@strengejacke These are still failing, when run non-interactively....

**Comment by strengejacke** [comment]
@IndrajeetPatil we maybe should default verbose to FALSE for the next update round?

**Comment by IndrajeetPatil** [comment]
Yes, sounds good.

**Pull request merged**
