### PR TITLE
Rollback to R3.4

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by strengejacke** [comment]
Checks will fail for now, because of https://github.com/easystats/bayestestR/commit/17a9634672959359e048d8e8435512b236b8c66a.

However, if we don't need to update bayestestR this round, but I don't see any urgent stuff for updates. So we may set R dependency to 3.4 on GitHub already, or not? @DominiqueMakowski ?

**Comment by mattansb** [comment]
Sounds right to me.

**Comment by strengejacke** [comment]
Ok, set back to 3.4 again (https://github.com/easystats/bayestestR/commit/b34e2654370cf1bb89aef92ae7c59b1cfbfb6782) - you may restart tests...

**Comment by mattansb** [comment]
@strengejacke any idea why it's still failing on 3.4?

**Comment by strengejacke** [comment]
> Warning: file ‘hardlyworking.RData’ has magic number 'RDX3'

See `?save`, the `version` argument. You must save the data in a version that's compatible with R < 3.5

**Comment by mattansb** [comment]
Ah, got it. I'll take a look at that later then :/

**Comment by mattansb** [comment]
Nope, that didn't fix it.

I think it's because in `bayestestR`s description, the lists the CRAN version `insight` instead of pointing to the "remotes" on GH.
@DominiqueMakowski @strengejacke could that be it?

**Comment by strengejacke** [comment]
It's a temporary issue:

> Error in utils::download.file(url, path, method = method, quiet = quiet,  :

**Comment by strengejacke** [comment]
I think we need to wait until bayestestR is on CRAN, then we can add back the `Remotes` field in the DESCRIPTION file, and then checks should pass.

**Comment by mattansb** [comment]
warnings in tests are due to https://github.com/easystats/insight/issues/287

**Comment by mattansb** [comment]
@strengejacke I'm merging this for now. Will deal with R3.4 when `bayestestR` is updated (though, in theory, there should be nothing to deal with)...

**Pull request merged**
