### PR TITLE
equivalence tests and plotting

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by mattansb** [comment]
waiting to see how this epic debate with @strengejacke https://github.com/easystats/parameters/issues/12 ends to decide if a `conditional = TRUE/FALSE` argument should be added for CET.

**Comment by strengejacke** [comment]
I'm adding a `rule` argument, with choices `"bayes"` (current implementation), `"lakens"`` and `"cet"`.

**Comment by mattansb** [comment]
Maybe change Lakens to something else? He didn't invent the rules :/
`c("et","cet","bayes")`?

**Comment by mattansb** [comment]
Taking this back to parameters

**Pull request merged**
