### PR TITLE
return rules' name as attribute (for report)

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by mattansb** [comment]
Might be a problem to use a "name" attribute, as it might conflict with "names". How about "rule_name"?

**Comment by DominiqueMakowski** [comment]
True, `rule_name` is good

**Comment by mattansb** [comment]
Doing it now

**Comment by mattansb** [comment]
Should be fine now - waiting for the tests to pass.
``` r

library(effectsize)

rules(c(-1,0,1), c("small", "meh-", "meh+", "BIG"))
#> # Reference thresholds (Custom rules)
#> 
#> small < -1 < meh- < 0 < meh+ < 1 < BIG

rules(c(-1,0,1), c("small", "meh-", "meh+", "BIG"), name = "IDK")
#> # Reference thresholds (IDK)
#> 
#> small < -1 < meh- < 0 < meh+ < 1 < BIG

(r <- rules(c(-1,1), c("small", "BIG"), name = "IDK"))
#> # Reference values (IDK)
#> 
#> small | BIG
#> -----------
#>    -1 |   1

interpret(-3:3, r)
#> [1] "small" "small" "small" "small" "BIG"   "BIG"   "BIG"  
#> 
#> (Rules: IDK)

interpret_r2(.02, r)
#> [1] "BIG"
#> 
#> (Rules: IDK)

(i <- interpret_r2(.02))
#> [1] "weak"
#> 
#> (Rules: cohen1988)

attr(i, "rule_name")
#> [1] "cohen1988"
```

<sup>Created on 2020-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Pull request merged**
