### PR TITLE
Perp for CRAN 0.4.1

### PR DESCRIPTION
**Pull request by mattansb**
"fix" d and g (with corrections) #222

And get ready to submit

### CODE REVIEW

**Comment by mattansb** [comment]
@DominiqueMakowski @strengejacke @IndrajeetPatil I will accept your acquiescence lol

Will merge and push to CRAN tomorrow

**Comment by mattansb** [comment]
@strengejacke Do you know why I'm getting this error on winbuilder? (https://win-builder.r-project.org/IKhGp60YV8Ux/00check.log)

>Package required and available but unsuitable version: 'parameters'

Locally, with parameters installed from CRAN, all checks pass...

**Comment by strengejacke** [comment]
> Locally, with parameters installed from CRAN, all checks pass...

You can ignore that. Seems like win-builder installs the latest CRAN packages _after_ binaries are built for Windows on CRAN - that may take some days / week(s).

**Comment by mattansb** [comment]
Stupid winbuilder.....

Submitting now.

**Comment by mattansb** [comment]
> `! LaTeX Error: There's no line here to end`

https://win-builder.r-project.org/incoming_pretest/effectsize_0.4.1_20201206_135637/Windows/00check.log
https://win-builder.r-project.org/incoming_pretest/effectsize_0.4.1_20201206_135637/Debian/00check.log

@IndrajeetPatil @strengejacke @DominiqueMakowski Any idea what this is? Or how I even debug this?
(I hope it's not because I used `styler`....)

**Comment by strengejacke** [comment]
You have to build the PDF manually (there is an R command line command) to find the bug. Resp. compile the generated .tex file with a Tex tool. I can do this later and try to find out the issue.

**Comment by mattansb** [comment]
@strengejacke Please do - I've tried on my computer, but couldn't figure out how to do it...

**Comment by strengejacke** [comment]
After `\itemize{}`, no empty lines are allowed.

**Comment by strengejacke** [comment]
How to debug such errors?

1. Install a [Tex-programme](https://miktex.org/)
2. Open the [windows command line](https://devblogs.microsoft.com/commandline/)
3. Add current R-file-path in the command line tool: `set PATH=C:\Program Files\R\R-4.0.3\bin\x64;%PATH%`
4. Run `R CMD Rd2pdf <filepath to effectsize folder>`, e.g. `R CMD Rd2pdf D:\mail\Documents\Coding\R\easystats\effectsize`.
5. In your user directory, you'll find a tex-file and a PDF, if successful. If not, open the `Rd2.tex` file, and compile. In your case, there were two `\cr` after the itemize block:

image

I had this issue before, so I caught that quite quickly...

**Comment by DominiqueMakowski** [comment]
Thanks Daniel that's good to know!

**Comment by mattansb** [comment]
Awesome, thanks for the tutorial and the fix!

**Comment by mattansb** [comment]
Added it here:

https://github.com/easystats/easystats/wiki/Debugging-LaTeX-issues

**Comment by strengejacke** [comment]
Great! I added some sentences, to provide more context and we understand it later as well. ;-)

**Comment by strengejacke** [comment]
btw, is _effectisze_ ready to submit? Would like to wait for it before submitting insight (deadline coming closer), so we can already add `format_table()` as alias to `parameters_table()`...

**Comment by mattansb** [comment]
oh, I just submitted....
But hopefully, after the JOSS paper is accepted, we can have a quick update soonish (:

**Comment by mattansb** [comment]
Okay lol it just failed with a stupid note, so we can wait for Insight (though I'm not sure if the current version of effectsize had use for those extra-new features?)

(and maybe also wait for the JOSS paper if it doesn't take too long? What do you think?)

**Comment by mattansb** [comment]
Oh, and just got an email from Uwe to ignore those notes 🤷‍♂️
what a roller-coaster!

**Comment by strengejacke** [comment]
No, I meant effectsize needs to be on CRAN before insight ;-) So go on, hurry up! 🤣

**Comment by strengejacke** [comment]
> though I'm not sure if the current version of effectsize had use for those extra-new features?

If you switched from `format_table()` to `export_table()` (and afaik, you did these changes), everything's fine.

**Comment by mattansb** [comment]
@IndrajeetPatil heads up for your stuff (:

**Comment by strengejacke** [comment]
@mattansb Did you change the column names for partial effect sizes?

https://cran.r-project.org/web/checks/check_results_parameters.html

**Comment by mattansb** [comment]
Yes, for one way between subject ANOVA, the "partial" is omitted as it is meaningless... See #180 :/

How did tests not catch this locally? :(

**Comment by strengejacke** [comment]
Yeah, I just saw it...

> For one-way between subjects designs, partial omega squared is equvilant to omega squared.
Returning omega squared.

**Comment by strengejacke** [comment]
Ok, I think I have to submit _parameters_ first, then _insight_ ;-)

**Pull request merged**
