### PR TITLE
CRAN 0.6.0

### PR DESCRIPTION
**Pull request by mattansb**
> Dear maintainer,
>
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_effectsize.html>.
> 
> Please correct before 2022-01-22 to safely retain your package on CRAN.
> 
> The CRAN Team

----

@strengejacke -- waiting for `parameters` 💪

### CODE REVIEW

**Comment by strengejacke** [comment]
Waiting for final checks (https://github.com/easystats/parameters), but everything seems to look good. Will submit today or tomorrow. _insight_ already broke _effectsize_, so there is "some hurry"...

**Comment by strengejacke** [comment]
btw, I suggest disabling "macOS-latest (oldrel) (pull_request)" checks - this currently seems to fail (installation of that OS).

**Comment by mattansb** [comment]
>  insight already broke effectsize, so there is "some hurry"...

Yeah, that's very odd :/

I have until 22/1 to submit.

**Comment by strengejacke** [comment]
> > insight already broke effectsize, so there is "some hurry"...
> 
> Yeah, that's very odd :/
> 
> I have until 22/1 to submit.

I'm not sure, maybe because insight broke parameters, and thus effectsize broke? Anyway, I think we will be able to submit everything in time.

**Comment by IndrajeetPatil** [comment]
I also have the same deadline for my packages and I would appreciate if you can get your packages online a bit before the deadline so that I have some breathing room during my submissions.

**Comment by mattansb** [comment]
> I also have the same deadline for my packages and I would appreciate if you can get your packages online a bit before the deadline so that I have some breathing room during my submissions.

I'm ready to go - as soon as parameters is up (:

**Comment by strengejacke** [comment]
_parameters_ on CRAN.

**Comment by mattansb** [comment]
Submitted.

@DominiqueMakowski note that this update breaks CRAN version of `report` (already fixed on GH).

**Comment by IndrajeetPatil** [comment]
@mattansb Of interest:

https://github.com/r-lib/urlchecker

**Pull request merged**
