### PR TITLE
check with latest dev versions

### PR DESCRIPTION
**Pull request by strengejacke**
# Description

This PR aims at adding this feature...

# Proposed Changes

I changed the `foo` function so that ...

### CODE REVIEW

**Comment by mattansb** [comment]
Do these errors make sense?

**Comment by strengejacke** [comment]
@mattansb seems like nothing needs to be done for _effectsize_ to work with the insight PR on the `get_data()` revision.

**Comment by IndrajeetPatil** [comment]
@strengejacke I think this PR can be closed?

**Comment by strengejacke** [comment]
Yes.

**Pull request closed without merging**
