### PR TITLE
new eta_squared_posterior + 0.3.2

### PR DESCRIPTION
**Pull request by mattansb**
# Description

This PR aims at adding this feature...

# Proposed Changes

I changed the `foo` function so that ...

### CODE REVIEW

**Comment by mattansb** [comment]
#107

**Comment by mattansb** [comment]
@DominiqueMakowski @strengejacke anyone have anything they'd like to add before I sent to CRAN?

**Comment by mattansb** [comment]
> package effectsize_0.3.2.tar.gz is on its way to CRAN.

**Comment by strengejacke** [comment]
> @DominiqueMakowski @strengejacke anyone have anything they'd like to add before I sent to CRAN?

No... or am I late to the party?

**Comment by mattansb** [comment]
Too late - good thing you didn't suddenly find some bug ;)

**Comment by strengejacke** [comment]
Wait, give me a minute...

**Pull request merged**
