### PR TITLE
ANOVA / diff ES and CIs

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by mattansb** [comment]
@DominiqueMakowski @strengejacke Travis help request; Getting weird fails... can you take a look?

**Comment by strengejacke** [comment]
Nothing serious, Travis fails to install R on OS X, it seems.

**Comment by mattansb** [comment]
Safe to merge then?

**Comment by strengejacke** [comment]
definitely.

**Comment by strengejacke** [comment]
(don't ask @DominiqueMakowski for merging, else you could be dying of old age before you get your go...)

**Comment by mattansb** [comment]
> (don't ask @DominiqueMakowski for merging, else you could be dying of old age before you get your go...)

😂😂😂👴

**Pull request merged**
