### PR TITLE
add p0 to OR conversion

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by mattansb** [comment]
Add test:

```R
library(effectsize)
library(testthat)

chen_tab_1 <- as.matrix(
  read.table(
    text = "p0      OR_1    OR_2    OR_3
        0.0100  1.6814  3.4739  6.7128
        0.0200  1.6146  3.1332  5.7486
        0.0300  1.5733  2.9535  5.2592
        0.0400  1.5455  2.8306  4.9471
        0.0500  1.5228  2.7416  4.7233
        0.0600  1.5060  2.6741  4.5536
        0.0700  1.4926  2.6177  4.4191
        0.0800  1.4811  2.5707  4.3097
        0.0900  1.4709  2.5309  4.2167
        0.1000  1.4615  2.4972  4.1387", 
    header = TRUE
  )
)

for (i in seq_len(nrow(chen_tab_1))) {
  d_recovered <- oddsratio_to_d(unname(chen_tab_1[i, 2:4]), p0 = chen_tab_1[i, 1])
  expect_equal(d_recovered, c(0.2, 0.5, 0.8), tolerance = 0.01)
}
```

**Comment by mattansb** [comment]
- [ ] need to add a `symmetric` argument to `rules()` that defines the point of symmetry for boundry-rules.
- [ ] Add support for matrix input/output

**Comment by mattansb** [comment]
So effectively, the `chen2010` rule is dropped - the default now is to use and OR to d transformation (possibly with `p0` provided) and interpreted according to Cohen's 0.2, 0.5, & 0.8 thresholds. 

@rempsyc this might break some tests in `report`?

**Comment by rempsyc** [comment]
> @rempsyc this might break some tests in `report`?

Solved, thanks!

**Pull request merged**
