### PR TITLE
submit to CRAN 0.3.3

### PR DESCRIPTION
**Pull request by mattansb**

### CODE REVIEW

**Comment by mattansb** [comment]
# CRAN message 

https://win-builder.r-project.org/incoming_pretest/effectsize_0.3.3_20200916_180537/Debian/00check.log
https://win-builder.r-project.org/incoming_pretest/effectsize_0.3.3_20200916_180537/Windows/00check.log

@strengejacke @DominiqueMakowski  help?

### 1. These URLs actually work... anything I can do about this? Or just write this as a message in the resubmission? 
```
Found the following (possibly) invalid URLs:
  URL: https://easystats.github.io/effectsize (moved to https://easystats.github.io/effectsize/)
    From: DESCRIPTION
    Status: 200
    Message: OK
  URL: https://easystats4u.shinyapps.io/statistic2effectsize/
    From: inst/doc/from_test_statistics.html
    Status: Error
    Message: libcurl error code 35:
      	schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).
```

### 2. What is this? I can't seem to find that this file exists...

```
* checking for non-standard things in the check directory ... NOTE
Found the following files/directories:
  ‘effectsize-manual.tex’
```

### 3. I think this use to work...? How can I tell where this is happening?

```
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! Package inputenc Error: Unicode char ε (U+3B5)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
! Package inputenc Error: Unicode char ω (U+3C9)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
! Package inputenc Error: Unicode char ε (U+3B5)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
! Package inputenc Error: Unicode char ω (U+3C9)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
* checking PDF version of manual without hyperrefs or index ... ERROR
```

**Comment by strengejacke** [comment]
at 1: add trailing slashes `/ ` - the other thing might be temporary

at 2: must be local on your hard disk? Just add `*.tex` to `.Rbuildignore`

at 3: build PDF manually, then you have access to the tex-logs for debugging. These are the most annoying errors.

**Comment by strengejacke** [comment]
The tex-thing (3) might be due to the special chars, you may need to include specific packages, or ensure different encoding?

**Comment by mattansb** [comment]
1 is fixed


(2 and 3 are related...)
I don't know what to do - there was no change to where those characters are created (in `\deqn{}` / `\eqn{}`), so why is this failing? Google has not been very useful..... :(((((

**Comment by mattansb** [comment]
Found them ! Those bastards!

**Comment by strengejacke** [comment]
@DominiqueMakowski I thought once _effectsize_ is updated on CRAN (which is rather "substantial" for _report_, I think), I plan to address some issues from _report_ and try to bring it in shape for initial CRAN submission...

**Comment by strengejacke** [comment]
Nice, all checks pass on GH-CI :-)

**Comment by mattansb** [comment]
having report on cran?? is it the end of times???

**Comment by mattansb** [comment]
> thanks, package effectsize_0.3.3.tar.gz is on its way to CRAN.

**Comment by DominiqueMakowski** [comment]
> @DominiqueMakowski I thought once effectsize is updated on CRAN (which is rather "substantial" for report, I think), I plan to address some issues from report and try to bring it in shape for initial CRAN submission...

🙏 hail lord @strengejacke

**Comment by strengejacke** [comment]
> > @DominiqueMakowski I thought once effectsize is updated on CRAN (which is rather "substantial" for report, I think), I plan to address some issues from report and try to bring it in shape for initial CRAN submission...
> 
> 🙏 hail lord @strengejacke

All that was written assuming that it will take some weeks until _effectsize_ will be accepted on CRAN. ;-)

**Pull request merged**
