### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by strengejacke** [comment]
Is [this commit](https://github.com/easystats/effectsize/pull/16/commits/36d0f009778694bf1a6cb370bbd0b04a5f216949) included in the build you submit to CRAN?

**Comment by DominiqueMakowski** [comment]
Haven't submitted yet I am still trying to have a passing version on winbuilder

**Comment by DominiqueMakowski** [comment]
Current version passes on winbuilder release: https://win-builder.r-project.org/BS8ypXg07i1d/00check.log

Running on devel and oldrel

**Comment by DominiqueMakowski** [comment]
```
Found the following (possibly) invalid URLs:
  URL: https://easystats.github.io/bayestestR/articles/4_Guidelines.html
    From: inst/doc/interpret.html
    Status: Error
    Message: libcurl error code 35:
      	error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
  URL: https://easystats.github.io/easystats/articles/interpret.html
    From: inst/doc/standardize_parameters.html
    Status: Error
    Message: libcurl error code 35:
      	error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
  URL: https://easystats.github.io/effectsize/reference/pooled_sd.html
    From: inst/doc/standardize_parameters.html
    Status: Error
    Message: libcurl error code 35:
      	error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

It's the only NOTE that is caught. It looks like a false positive.

**Comment by DominiqueMakowski** [comment]
@strengejacke @mattansb I'll be waiting for your greenlight to submit

**Comment by strengejacke** [comment]
https://easystats.github.io/easystats/articles/interpret.html

URL not found

**Comment by strengejacke** [comment]
https://easystats.github.io/effectsize/reference/pooled_sd.html

URL not found

**Comment by strengejacke** [comment]
As I said, dev-branch is a mess ;-)
Merge this PR, build the website and then everything should work (except the one URL above, where you reference the easystats-package)

**Comment by strengejacke** [comment]
https://easystats.github.io/bayestestR/articles/4_Guidelines.html

URL not found

**Comment by mattansb** [comment]
All good on my end

**Pull request merged**
