### PR TITLE
add interpretation rule for Kendall's w and some more 80-width styling

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
I can't find any guidelines for the other non-parametric effect sizes 😿

**Comment by mattansb** [comment]
Too bad (😄😄😄)

In addition to my other notes, please also add this to the interpretation vignette (:

**Comment by IndrajeetPatil** [comment]
Those two actions will continue to fail till binaries for `tibble 3.1.0` are built. Nothing I can do on my end 🤷‍♂️

**Comment by mattansb** [comment]
Where are we using tibble? 🤔

(Also, did you see my comments?)

**Comment by IndrajeetPatil** [comment]
No, `tibble` is used by packages needed by github actions. But that's resolved now. 

Sorry, which comments? I see no comments on the PR.

**Comment by mattansb** [comment]
lol forgot to click "submit review" 🤷‍♂️

**Comment by IndrajeetPatil** [comment]
Done!

**Review by mattansb — APPROVED** [review]

**Comment by mattansb** [comment]
Cool, thanks!

**Pull request merged**
