### PR TITLE
use check_if_installed

### PR DESCRIPTION
**Pull request by mattansb**
# Description

This PR aims at adding this feature...

# Proposed Changes

I changed the `foo` function so that ...

### CODE REVIEW

**Comment by mattansb** [comment]
Correct

**Comment by strengejacke** [comment]
> This means we will have to wait for the next release of insight before effectsize can be submitted to CRAN, right?

why?

**Comment by strengejacke** [comment]
Yeah, but why does it rely on GitHub? `check_if_installed()` is in the CRAN version.

**Comment by IndrajeetPatil** [comment]
Oh, that's because he made changes to this function in the `GitHub` version of `insight` and that's the version he is using:
https://github.com/easystats/insight/commit/f70a14f9cf7c29d5f0984bb08908df5a51dc5379

**Comment by IndrajeetPatil** [comment]
I think this is a good temporary solution to avoid having to wait for another month:
https://github.com/easystats/effectsize/pull/325

**Pull request merged**
